name: Keep Render and Supabase Alive

on:
  schedule:
    - cron: '0 0 */6 * *'
  workflow_dispatch:

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Send Ping Request
        run: |
          curl -I -s -X GET "https://club-portal-4l6w.onrender.com"